### ISSUE TITLE
error: unknown command 'generate'

### ISSUE THREAD

**Issue by ciraos** [lete114/AWStats#1]
nodejs版本为`18.12.1`，环境变量安装正常。

![](https://cdn.jsdelivr.net/gh/ciraos/ciraos-static@main/img/2022-12-04-09-30-30.png)

执行`awstats srver`的时候出现如下错误：

``` yaml
error: unknown command 'server'
```

其他指令例如`clean`、`generate `、`deploy`、`minify`，均会出现此类报错，难道是因为我node版本太高了吗？

**Comment by lete114** [comment]
需要安装awstats-cli
npm i -g awstats-cli

**Comment by ciraos** [comment]
可以了，是我的node安装方式错了。
